### ISSUE TITLE
Release 2.0.3 has no images in the dist folder

### ISSUE THREAD

**Issue by ErikNijland** [ljagis/leaflet-measure#60]
Since 2.0.3 the CSS file has references to missing images. It is working in version 2.0.2.

**Comment by brandoncopeland** [comment]
Thanks. Fixing now.

**Comment by brandoncopeland** [comment]
fixed @ commit c340e90

**Comment by ErikNijland** [comment]
Thanks for the quick fix. But I'm afraid you forgot (at least) one icon; the start icon is missing (circle with a play icon in it).

**Comment by brandoncopeland** [comment]
Sorry. It's been that kind of day. Check now at 2.0.5.

**Comment by ErikNijland** [comment]
Solved! Thanks.
